version: "3.7"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure
    networks:
      - simple-microservices

networks:
  simple-microservices:
    name: simple-microservices-network